# Thanks to https://github.com/jerry80409
# Reference: https://github.com/jerry80409/distrise/blob/dev2/docker/docker-compose.yaml

version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach:v22.2.9
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: ${DB_NAME}
      COCKROACH_USER: ${DB_USER}
      COCKROACH_PASSWORD: ${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "26257:26257"
      - "8090:8080"
    volumes:
      - cockroachdb:/cockroach/cockroach-data
  rabbitmq:
    image: rabbitmq:3.11.16
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ~/log/rabbitmq:/var/log/rabbitmq
  relay:
    depends_on:
      - cockroach
    build:
      context: .
      dockerfile: relay.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:$SERVER_PORT
    stdin_open: true
    tty: true
  aggregator:
    depends_on:
      - cockroach
      - rabbitmq
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    env_file: .env
    ports:
      - 8081:$SERVER_PORT
    stdin_open: true
    tty: true
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   command: [--config=/etc/otel-collector-config.yaml]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension

volumes:
  cockroachdb:
