# Thanks to https://github.com/jerry80409
# Reference: https://github.com/jerry80409/distrise/blob/dev2/docker/docker-compose.yaml

version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach:v22.2.9
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: ${DB_NAME}
      COCKROACH_USER: ${DB_USER}
      COCKROACH_PASSWORD: ${DB_PASSWORD}
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroachdb:/cockroach/cockroach-data

volumes:
  cockroachdb:
