# Thanks to https://github.com/jerry80409
# Reference: https://github.com/jerry80409/distrise/blob/dev2/docker/docker-compose.yaml

version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach:v22.2.9
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: ${DB_NAME}
      COCKROACH_USER: ${DB_USER}
      COCKROACH_PASSWORD: ${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "26257:26257"
      - "8090:8080"
    volumes:
      - cockroachdb:/cockroach/cockroach-data
  rabbitmq:
    image: rabbitmq:3.11.16
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/log/rabbitmq:/var/log/rabbitmq
  relay:
    depends_on:
      - cockroach
    build:
      context: .
      dockerfile: relay.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:$SERVER_PORT
    stdin_open: true
    tty: true
  aggregator:
    depends_on:
      - cockroach
      - rabbitmq
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    env_file: .env
    ports:
      - 8081:$SERVER_PORT
    stdin_open: true
    tty: true

volumes:
  cockroachdb:
